import{a as w,S as L,i as E}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const P="https://pixabay.com",S="44423269-f21c5bc9414954348df27e7dd";async function m(t,r=1,n=15){const l="/api/",e=new URLSearchParams({key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}),o=`${P}${l}?${e}`;try{const s=await w.get(o);if(s.status!==200)throw new Error("Network response was not ok");return s.data}catch(s){throw console.error("Error fetching images:",s),s}}let p;function h(t,r=!1){const n=document.getElementById("gallery"),l=t.map(e=>`
      <a href="${e.largeImageURL}" data-lightbox="gallery">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}" />
          <p>${e.tags}</p>
        </div>
      </a>
    `).join("");r?n.insertAdjacentHTML("beforeend",l):n.innerHTML=l,p?p.refresh():p=new L(".gallery a",{})}function y(t){E.error({title:"Error",message:t})}function q(){const t=document.getElementById("gallery");t.innerHTML=""}const i=document.querySelector(".loader-wrapper"),d=document.querySelector(".load-more"),c=document.createElement("p");c.textContent="We're sorry, but you've reached the end of search results.";c.style.display="none";document.body.appendChild(c);let a=1,u="",f=0;const g={form:document.querySelector(".js-picture-form"),input:document.querySelector('.js-picture-form input[name="query"]'),gallery:document.getElementById("gallery")};g.form.addEventListener("submit",async function(t){t.preventDefault();const r=g.input.value.trim();if(r===""){y("Please enter a search term");return}r!==u&&(u=r,a=1,f=0,q(),d.style.display="none",c.style.display="none"),i.style.display="block";try{const n=await m(u,a);i.style.display="none",f=n.totalHits,n.hits.length===0?y("Sorry, there are no images matching your search query. Please try again!"):(h(n.hits,a>1),a*15<f?d.style.display="block":(d.style.display="none",c.style.display="block"),a>1&&b())}catch{i.style.display="none",y("An error occurred while fetching the images. Please try again.")}});d.addEventListener("click",async function(){a+=1,i.style.display="block";try{const t=await m(u,a);i.style.display="none",h(t.hits,!0),a*15>=f&&(d.style.display="none",c.style.display="block"),b()}catch{i.style.display="none",y("An error occurred while fetching the images. Please try again.")}});function v(){const r=document.querySelector("#gallery").querySelector(".image-card");return r?r.getBoundingClientRect().height:0}function b(){const t=v();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
