import{S as f,i as d}from"./assets/vendor-8c59ed88.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="https://pixabay.com",y="44423269-f21c5bc9414954348df27e7dd";function p(o){const n="/api/",r=new URLSearchParams({key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),s=`${m}${n}?${r}`;return fetch(s).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).catch(e=>{throw console.error("Error fetching images:",e),e})}let a;function g(o){const n=document.getElementById("gallery");n.innerHTML=o.map(r=>`
      <a href="${r.largeImageURL}" data-lightbox="gallery">
        <div class="image-card">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <p>${r.tags}</p>
        </div>
      </a>
    `).join(""),a?a.refresh():a=new f(".gallery a",{})}function c(o){d.error({title:"Error",message:o})}function h(){const o=document.getElementById("gallery");o.innerHTML=""}const l=document.querySelector(".loader-wrapper"),u={form:document.querySelector(".js-picture-form"),input:document.querySelector('.js-picture-form input[name="query"]'),gallery:document.getElementById("gallery")};u.form.addEventListener("submit",function(o){o.preventDefault();const n=u.input.value.trim();if(n===""){c("Please enter a search term");return}h(),l.style.display="block",p(n).then(r=>{l.style.display="none",r.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):g(r.hits)}).catch(r=>{l.style.display="none",c("An error occurred while fetching the images. Please try again.")})});
//# sourceMappingURL=commonHelpers.js.map
